#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['croniter', 'croniter.tests']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['python_dateutil']

setup(name='croniter',
      version='6.2.0',
      description='croniter provides iteration for datetime object with cron like format',
      author=None,
      author_email='Matsumoto Taichi <taichino@gmail.com>, kiorky <kiorky@cryptelium.net>, Ash Berlin-Taylor <ash@apache.org>, Jarek Potiuk <jarek@potiuk.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      python_requires='>=3.9',
     )
